// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: muxcore/inputvalidate/v1/inputvalidate.proto

package inputvalidatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InputValidateService_Validate_FullMethodName         = "/muxcore.inputvalidate.v1.InputValidateService/Validate"
	InputValidateService_SupportedSchemas_FullMethodName = "/muxcore.inputvalidate.v1.InputValidateService/SupportedSchemas"
)

// InputValidateServiceClient is the client API for InputValidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InputValidateServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	SupportedSchemas(ctx context.Context, in *SupportedSchemasRequest, opts ...grpc.CallOption) (*SupportedSchemasResponse, error)
}

type inputValidateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInputValidateServiceClient(cc grpc.ClientConnInterface) InputValidateServiceClient {
	return &inputValidateServiceClient{cc}
}

func (c *inputValidateServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, InputValidateService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inputValidateServiceClient) SupportedSchemas(ctx context.Context, in *SupportedSchemasRequest, opts ...grpc.CallOption) (*SupportedSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportedSchemasResponse)
	err := c.cc.Invoke(ctx, InputValidateService_SupportedSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputValidateServiceServer is the server API for InputValidateService service.
// All implementations must embed UnimplementedInputValidateServiceServer
// for forward compatibility.
type InputValidateServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	SupportedSchemas(context.Context, *SupportedSchemasRequest) (*SupportedSchemasResponse, error)
	mustEmbedUnimplementedInputValidateServiceServer()
}

// UnimplementedInputValidateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInputValidateServiceServer struct{}

func (UnimplementedInputValidateServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedInputValidateServiceServer) SupportedSchemas(context.Context, *SupportedSchemasRequest) (*SupportedSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SupportedSchemas not implemented")
}
func (UnimplementedInputValidateServiceServer) mustEmbedUnimplementedInputValidateServiceServer() {}
func (UnimplementedInputValidateServiceServer) testEmbeddedByValue()                              {}

// UnsafeInputValidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InputValidateServiceServer will
// result in compilation errors.
type UnsafeInputValidateServiceServer interface {
	mustEmbedUnimplementedInputValidateServiceServer()
}

func RegisterInputValidateServiceServer(s grpc.ServiceRegistrar, srv InputValidateServiceServer) {
	// If the following call panics, it indicates UnimplementedInputValidateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InputValidateService_ServiceDesc, srv)
}

func _InputValidateService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputValidateServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputValidateService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputValidateServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InputValidateService_SupportedSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputValidateServiceServer).SupportedSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InputValidateService_SupportedSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputValidateServiceServer).SupportedSchemas(ctx, req.(*SupportedSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InputValidateService_ServiceDesc is the grpc.ServiceDesc for InputValidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InputValidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.inputvalidate.v1.InputValidateService",
	HandlerType: (*InputValidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _InputValidateService_Validate_Handler,
		},
		{
			MethodName: "SupportedSchemas",
			Handler:    _InputValidateService_SupportedSchemas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "muxcore/inputvalidate/v1/inputvalidate.proto",
}
