// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: muxcore/inputvalidate/v1/inputvalidate.proto

package inputvalidatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ValidateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Sanitized     []byte                 `protobuf:"bytes,3,opt,name=sanitized,proto3" json:"sanitized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateResponse) GetSanitized() []byte {
	if x != nil {
		return x.Sanitized
	}
	return nil
}

type SupportedSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedSchemasRequest) Reset() {
	*x = SupportedSchemasRequest{}
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedSchemasRequest) ProtoMessage() {}

func (x *SupportedSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedSchemasRequest.ProtoReflect.Descriptor instead.
func (*SupportedSchemasRequest) Descriptor() ([]byte, []int) {
	return file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescGZIP(), []int{2}
}

type SupportedSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []string               `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedSchemasResponse) Reset() {
	*x = SupportedSchemasResponse{}
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedSchemasResponse) ProtoMessage() {}

func (x *SupportedSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedSchemasResponse.ProtoReflect.Descriptor instead.
func (*SupportedSchemasResponse) Descriptor() ([]byte, []int) {
	return file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescGZIP(), []int{3}
}

func (x *SupportedSchemasResponse) GetSchemas() []string {
	if x != nil {
		return x.Schemas
	}
	return nil
}

var File_muxcore_inputvalidate_v1_inputvalidate_proto protoreflect.FileDescriptor

const file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDesc = "" +
	"\n" +
	",muxcore/inputvalidate/v1/inputvalidate.proto\x12\x18muxcore.inputvalidate.v1\"=\n" +
	"\x0fValidateRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"^\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1c\n" +
	"\tsanitized\x18\x03 \x01(\fR\tsanitized\"\x19\n" +
	"\x17SupportedSchemasRequest\"4\n" +
	"\x18SupportedSchemasResponse\x12\x18\n" +
	"\aschemas\x18\x01 \x03(\tR\aschemas2\xf4\x01\n" +
	"\x14InputValidateService\x12a\n" +
	"\bValidate\x12).muxcore.inputvalidate.v1.ValidateRequest\x1a*.muxcore.inputvalidate.v1.ValidateResponse\x12y\n" +
	"\x10SupportedSchemas\x121.muxcore.inputvalidate.v1.SupportedSchemasRequest\x1a2.muxcore.inputvalidate.v1.SupportedSchemasResponseB]Z[github.com/Muxcore-Media/input-validate-jsonschema/muxcore/inputvalidate/v1;inputvalidatev1b\x06proto3"

var (
	file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescOnce sync.Once
	file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescData []byte
)

func file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescGZIP() []byte {
	file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescOnce.Do(func() {
		file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDesc), len(file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDesc)))
	})
	return file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDescData
}

var file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_muxcore_inputvalidate_v1_inputvalidate_proto_goTypes = []any{
	(*ValidateRequest)(nil),          // 0: muxcore.inputvalidate.v1.ValidateRequest
	(*ValidateResponse)(nil),         // 1: muxcore.inputvalidate.v1.ValidateResponse
	(*SupportedSchemasRequest)(nil),  // 2: muxcore.inputvalidate.v1.SupportedSchemasRequest
	(*SupportedSchemasResponse)(nil), // 3: muxcore.inputvalidate.v1.SupportedSchemasResponse
}
var file_muxcore_inputvalidate_v1_inputvalidate_proto_depIdxs = []int32{
	0, // 0: muxcore.inputvalidate.v1.InputValidateService.Validate:input_type -> muxcore.inputvalidate.v1.ValidateRequest
	2, // 1: muxcore.inputvalidate.v1.InputValidateService.SupportedSchemas:input_type -> muxcore.inputvalidate.v1.SupportedSchemasRequest
	1, // 2: muxcore.inputvalidate.v1.InputValidateService.Validate:output_type -> muxcore.inputvalidate.v1.ValidateResponse
	3, // 3: muxcore.inputvalidate.v1.InputValidateService.SupportedSchemas:output_type -> muxcore.inputvalidate.v1.SupportedSchemasResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_muxcore_inputvalidate_v1_inputvalidate_proto_init() }
func file_muxcore_inputvalidate_v1_inputvalidate_proto_init() {
	if File_muxcore_inputvalidate_v1_inputvalidate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDesc), len(file_muxcore_inputvalidate_v1_inputvalidate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_muxcore_inputvalidate_v1_inputvalidate_proto_goTypes,
		DependencyIndexes: file_muxcore_inputvalidate_v1_inputvalidate_proto_depIdxs,
		MessageInfos:      file_muxcore_inputvalidate_v1_inputvalidate_proto_msgTypes,
	}.Build()
	File_muxcore_inputvalidate_v1_inputvalidate_proto = out.File
	file_muxcore_inputvalidate_v1_inputvalidate_proto_goTypes = nil
	file_muxcore_inputvalidate_v1_inputvalidate_proto_depIdxs = nil
}
